### PR TITLE
Lukas/object detail

### PR DESCRIPTION
**Pull request by lukasvaz**
ObjectDetail View:
- you can ascces to it   in the following url : gallery/object:id
- merging conflicts solved
- you  need to store pieces-models folder locally  in ./public  to visualize objects.

image

### CODE REVIEW

**Review by IsaiasVenegas — CHANGES_REQUESTED** [review]
Hi Lukas, nice work but requires some changes:
* Object title should be in bold and not include "ID" in it.
* "Descargar" and "Editar pieza" buttons should not appear if there is no active user session. "Solicitar pieza" should appear instead.
* "Editar pieza" has a weird right margin (maybe you can do it like you did with the tags)
* "Cultura" and "Forma" chips should have a background color. Please define them as #FEE2DD and #D2E5EF respectively in `styles.js`.

**Comment by lukasvaz** [comment]
- Tags colors added  to style.js
-  refactoring  margin in option panel (Descarga Solicitar Pieza etc)
- Download  form was removed to  keep just  final  code  in main frontend-branch
- rendering options according loggedUser
-  not logged
image
-logged
image

**Comment by lukasvaz** [comment]
adding  carousel  component  to display images :
image

adding functional form  to download data for unlogged  users:
image

**Review by IsaiasVenegas — APPROVED** [review]
Nice

**Pull request merged**
